### ISSUE TITLE
Sandbox mode

### ISSUE THREAD

**Issue by ghost** [asciutto990/Stripe-and-Plaid-Link-.NET#1]
Is that possible to test in sandbox mode?

I have seen the below url in PlaidHttpClient, What is the purpose of this URL?
https://tartan.plaid.com

Can you support the below API Host url?
API Host: 
https://sandbox.plaid.com (Sandbox)
https://development.plaid.com (Development)
https://production.plaid.com (Production)

**Comment by asciutto990** [comment]
When this repo was created, testing was done against their tartan api, and all production requests were made against api.plaid.com as the base url. If you have the time, you may open a pull request with your changes to handle the new base urls provided in their documentation.

**Comment by asciutto990** [comment]
Changes have been pushed. You may now select 1 of 5 environments.

**Comment by ghost** [comment]
Thanks.
